
# https://www.rforseo.com/ressources/launch-an-r-script-using-github-actions
# https://blog.rmhogervorst.nl/blog/2020/09/24/running-an-r-script-on-a-schedule-gh-actions/

name: Data Pipeline

# Controls when the action will run 
on: 
  schedule:
    - cron: '0 13 * * *'
  push:
    branches: [main, master]


jobs:
  scrape:
    name: narcan data refresh main 
    runs-on: ubuntu-latest
    container:
      image: myominnoo/rstudio:4.3.2
    steps: 
      - name: checkout_repo
        uses: actions/checkout@v2
        with:
          ref: "main"
    # Step 2: Get the latest data and store it as a CSV
    - name: Fetch latest data
      run: Rscript -e "RSocrata::read.socrata('https://data.winnipeg.ca/resource/qd6b-q49i.json') -> df; print(head(df)); readr::write_csv(x = df, file = 'data/narcan.csv', append = FALSE)"    
    # Step 3: Commit and push
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push