
# https://www.rforseo.com/ressources/launch-an-r-script-using-github-actions
# https://blog.rmhogervorst.nl/blog/2020/09/24/running-an-r-script-on-a-schedule-gh-actions/

name: Data Pipeline

# Controls when the action will run 
on: 
  schedule:
    - cron: '0 13 * * *'
  push:
    branches: [main, master]


jobs:
  data_refresh_staging:
    name: narcan data refresh main 
    runs-on: ubuntu-latest
    container:
      image: myominnoo/rstudio:4.3.2
    steps: 
      - name: checkout_repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    # Step 2: Get the latest data and store it as a CSV
    - name: Fetch latest data
      run: curl 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.csv' -o usgs_current.csv
    # Step 3: Commit and push
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push